/**
 * Staff portrait paths (local). Generated by scripts/download-leadership-photos.mjs — re-run after updating CBC photos.
 * Names missing here use initials placeholder in the UI.
 */
export const staffPhotos: Record<string, string> = {
  "Aaron Austin": "/images/leadership/aaron-austin.webp",
  "Brenda Croucher": "/images/leadership/brenda-croucher.png",
  "Brian Carroll": "/images/leadership/brian-carroll.jpg",
  "Chris Chapel": "/images/leadership/chris-chapel.jpg",
  "Christine Redinger": "/images/leadership/christine-redinger.png",
  "Dave Edwards": "/images/leadership/dave-edwards.jpg",
  "Desi Pocklington": "/images/leadership/desi-pocklington.png",
  "Elbert Robles": "/images/leadership/elbert-robles.jpg",
  "Jason Wolin": "/images/leadership/jason-wolin.jpg",
  "Jenni Escobar": "/images/leadership/jenni-escobar.jpg",
  "Jim Archer": "/images/leadership/jim-archer.jpg",
  "Jim Arnold": "/images/leadership/jim-arnold.jpg",
  "John Perez": "/images/leadership/john-perez.jpg",
  "Jonathan Chang": "/images/leadership/jonathan-chang.png",
  "Jose Nevarez": "/images/leadership/jose-nevarez.jpg",
  "Marc Coates": "/images/leadership/marc-coates.jpg",
  "Margaret Welch": "/images/leadership/margaret-welch.jpg",
  "Mark Cory": "/images/leadership/mark-cory.jpg",
  "Mike McGinty": "/images/leadership/mike-mcginty.jpg",
  "Nathan Anderson": "/images/leadership/nathan-anderson.png",
  "Pat Stone": "/images/leadership/pat-stone.jpg",
  "Regina Lopez": "/images/leadership/regina-lopez.jpg",
  "Ron Galle": "/images/leadership/ron-galle.jpg",
  "Sonya Stone": "/images/leadership/sonya-stone.png",
  "Tim Weaver": "/images/leadership/tim-weaver.jpg",
  "Wes Hill": "/images/leadership/wes-hill.jpg",
  "Whitney Tuthill": "/images/leadership/whitney-tuthill.png",
  "William Michael": "/images/leadership/william-michael.jpg"
};
